sonar.projectKey=reinaldogez_fiap-cloud-games-mvp
sonar.organization=reinaldogez
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.coverage.exclusions=**/Migrations/**
sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**
