<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Fcg.Identity.Domain\Fcg.Identity.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fcg.Contracts" Version="1.0.0" />
    <PackageReference Include="MassTransit.Abstractions" Version="8.5.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
