name: CI

on:
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Testes Unitários
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Testes Unitários
        run: dotnet test tests/FCG.Tests.Unit/ --no-build --configuration Release --verbosity normal

  integration-tests:
    name: Testes de Integração
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Testes de Integração
        run: dotnet test tests/FCG.Tests.Integration/ --no-build --configuration Release --verbosity normal
        env:
          Jwt__SigningKey: ${{ secrets.JWT_SIGNING_KEY }}
          Jwt__Issuer: "FcgApi.Tests"
          Jwt__Audience: "FcgClients.Tests"
          AdminSeed__DefaultPassword: ${{ secrets.ADMIN_SEED_PASSWORD }}
